### ISSUE TITLE
Fix OS Builds github workflow

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/deep-memo-app#138]
<details>
  <summary>Description</summary>

[OS Builds github workflow falls with error](https://github.com/deep-foundation/deep-memo-app/actions/runs/7206567841/job/19631658968)

</details>

<details>
  <summary>Questions</summary>

<details>
  <summary>Why is `build-electron` script not used before `cd electron` to generate fresh electron folder?</summary>

`build-electron` script:  
https://github.com/deep-foundation/deep-memo-app/blob/4552d5a7a712b260a8329a59f22634d1f281fbd4/package.json#L25

Step with `cd electron`:  
https://github.com/deep-foundation/deep-memo-app/blob/f4228339fcc1310a8c6957b88c9d23ac92f79ad1/.github/workflows/os-builds.yaml#L55-L56

</details>

<details>
  <summary>Why `--force` option is used for `npm ci`?</summary>

https://github.com/deep-foundation/deep-memo-app/blob/f4228339fcc1310a8c6957b88c9d23ac92f79ad1/.github/workflows/os-builds.yaml#L53-L54

</details>

</details>

**Comment by FreePhoenix888** [comment]
Commits I have done:
- https://github.com/deep-foundation/deep-memo-app/commit/982b63e25ff83b58027211ada68a2442c369da0f
- https://github.com/deep-foundation/deep-memo-app/commit/52e31e68bceda89f21f29001716a272eefdc87fb

New error: https://github.com/deep-foundation/deep-memo-app/actions/runs/7206827139/job/19632419281

Why does this error occur? We have electron-unhandled dependency in both `package.json` and `package-lock.json`:
https://github.com/deep-foundation/deep-memo-app/blob/52e31e68bceda89f21f29001716a272eefdc87fb/electron/package.json#L33
https://github.com/deep-foundation/deep-memo-app/blob/52e31e68bceda89f21f29001716a272eefdc87fb/electron/package-lock.json#L1834-L1845

**Comment by FreePhoenix888** [comment]
Error: https://github.com/deep-foundation/deep-memo-app/actions/runs/7219140330/job/19669641858
Why do we need to pull latest deeplinks from repo? https://github.com/deep-foundation/deep-memo-app/blob/d87b125e92be85c7f9796761f065e1cde35d00d4/.github/workflows/os-builds.yaml#L57-L58

**Comment by FreePhoenix888** [comment]
https://github.com/deep-foundation/deep-memo-app/actions/runs/7220293841/job/19672925219

**Comment by FreePhoenix888** [comment]
I have fixed linux build: https://github.com/deep-foundation/deep-memo-app/actions/runs/7220828439/job/19674532971

**Comment by ivansglazunov** [comment]
> <details>
> 
>   <summary>Description</summary>
> 
> 
> 
> [OS Builds github workflow falls with error](https://github.com/deep-foundation/deep-memo-app/actions/runs/7206567841/job/19631658968)
> 
> 
> 
> </details>
> 
> 
> 
> <details>
> 
>   <summary>Questions</summary>
> 
> 
> 
> <details>
> 
>   <summary>Why is `build-electron` script not used before `cd electron` to generate fresh electron folder?</summary>
> 
> 
> 
> `build-electron` script:  
> 
> https://github.com/deep-foundation/deep-memo-app/blob/4552d5a7a712b260a8329a59f22634d1f281fbd4/package.json#L25
> 
> 
> 
> Step with `cd electron`:  
> 
> https://github.com/deep-foundation/deep-memo-app/blob/f4228339fcc1310a8c6957b88c9d23ac92f79ad1/.github/workflows/os-builds.yaml#L55-L56
> 
> 
> 
> </details>
> 
> 
> 
> <details>
> 
>   <summary>Why `--force` option is used for `npm ci`?</summary>
> 
> 
> 
> https://github.com/deep-foundation/deep-memo-app/blob/f4228339fcc1310a8c6957b88c9d23ac92f79ad1/.github/workflows/os-builds.yaml#L53-L54
> 
> 
> 
> </details>
> 
> 
> 
> </details>
> 
> 
> 
> 
> 
> 
> 
> 

Force need for ignore not critical versions conflict

**Comment by FreePhoenix888** [comment]
I have fixed mac build: https://github.com/deep-foundation/deep-memo-app/actions/runs/7230652016/job/19702947915

**Comment by FreePhoenix888** [comment]
I have fixed windows build: https://github.com/deep-foundation/deep-memo-app/actions/runs/7230860631/job/19703403317

**Comment by FreePhoenix888** [comment]
The first release is executed successfully: https://github.com/deep-foundation/deep-memo-app/actions/runs/7230898644
https://github.com/deep-foundation/deep-memo-app/releases/tag/0.0.1-dev.0

**Comment by FreePhoenix888** [comment]
There are some hardcoded versions in github workflow, I need to fix that

**Comment by FreePhoenix888** [comment]
https://github.com/deep-foundation/deep-memo-app/actions/runs/7231467323
https://github.com/deep-foundation/deep-memo-app/releases/tag/0.0.1-dev.1
